### ISSUE TITLE
TypeError : Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by djdembeck** [djdembeck/audnexus#4]
ASIN: `B00WNBF0RM`
```
[2021-09-07T02:54:40.265Z] INFO  aorus-283611/API: => GET /book?asin=B00WNBF0RM
[2021-09-07T02:54:40.267Z] INFO  aorus-283611/API:    Call 'book.getBook' action
[2021-09-07T02:54:41.544Z] INFO  aorus-283611/TRACER: ┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
[2021-09-07T02:54:41.544Z] INFO  aorus-283611/TRACER: │ ID: dceea731-24ad-4111-bfbd-9a9f9a1094c3                                       Depth: 2 Total: 2 │
[2021-09-07T02:54:41.545Z] INFO  aorus-283611/TRACER: ├──────────────────────────────────────────────────────────────────────────────────────────────────┤
[2021-09-07T02:54:41.545Z] INFO  aorus-283611/TRACER: │ GET /api/book?asin=B00WNBF0RM ×                    1s [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■] │
[2021-09-07T02:54:41.545Z] INFO  aorus-283611/TRACER: │ └─── action 'book.getBook' ×                       1s [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■.] │
[2021-09-07T02:54:41.545Z] INFO  aorus-283611/TRACER: └──────────────────────────────────────────────────────────────────────────────────────────────────┘
[2021-09-07T02:54:41.545Z] ERROR aorus-283611/API:    Request error! TypeError : Cannot read property 'length' of undefined 
 TypeError: Cannot read property 'length' of undefined
    at stitchHelper.setSeriesOrder (/home/djdembeck/projects/audnexus/helpers/audibleStitch.js:17:24)
    at stitchHelper.process (/home/djdembeck/projects/audnexus/helpers/audibleStitch.js:34:14)
    at /home/djdembeck/projects/audnexus/services/book.service.js:52:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.handler (/home/djdembeck/projects/audnexus/services/book.service.js:50:24)
    at async Service.callAction (/home/djdembeck/projects/audnexus/node_modules/moleculer-web/src/index.js:621:16)
    at async /home/djdembeck/projects/audnexus/node_modules/moleculer-web/src/index.js:446:22 
Data: undefined

```

**Comment by djdembeck** [comment]
Fixed by https://github.com/djdembeck/audnexus/commit/307fce958b2ba237f11197bc008eaa6affbd947c
